### ISSUE TITLE
repo page 500 because of markdown render error

### ISSUE THREAD

**Issue by allenfoxtc** [go-gitea/gitea#10842]
- Gitea version (or commit ref):
- Git version:
- Operating system:
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:
fatal from goldmark: interface conversion: interface {} is string, not []uint8
## Description
i reproduce it on try.gitea.io: [Link](https://try.gitea.io/fox/ShadowsocksX-NG-R8)
but the README.md is rendering just fine on [goldmark demo page](https://spec.commonmark.org/dingus/)
...

**Comment by jolheiser** [comment]
For anyone who looks in to this, you can get the README contents [here](https://try.gitea.io/fox/ShadowsocksX-NG-R8/raw/branch/develop/README.md)

**Comment by zeripath** [comment]
Damn this is something to do with the checkbox change I made...

```
## TODO List

- [x] Embed the http proxy server [privoxy](http://www.privoxy.org/), [get it](https://homebrew.bintray.com/bottles/privoxy-3.0.26.sierra.bottle.tar.gz).


- [x] ACL mode support [Shadowsocks ACL](https://github.com/shadowsocksr/shadowsocksr-libev/tree/master/acl)
```

Appears to be the bit that kills things

**Comment by zeripath** [comment]
FFS! I did actually test that change but then noticed the SetAttributeString and must not have properly tested again!
