### ISSUE TITLE
Task list bug when using capital X as completed (1.11.4)

### ISSUE THREAD

**Issue by xoac** [go-gitea/gitea#11317]
- Gitea version (or commit ref):1.11.4 (docker alpine version)
- Git version: not relavant 
- Operating system: Ubuntu 18 LTS
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description
Task counter doesn't count on capital X. Count task manually on screenshot. 

## Screenshots
![image](https://user-images.githubusercontent.com/1863020/81280944-82d97580-9059-11ea-992e-e27a1fc64347.png)
![image](https://user-images.githubusercontent.com/1863020/81280979-8f5dce00-9059-11ea-880f-3bc6cfbcf897.png)
![image](https://user-images.githubusercontent.com/1863020/81281646-67229f00-905a-11ea-91b9-e66573c86ce9.png)

**Comment by xoac** [comment]
I have also tried this bug at try gitea and it was not present on gitea 1.12.0+dev-269-gb16534b0e

But I have noticed I can't see issues after doing this:
```
- [] no space in task point 
- [ ] space in task point
```

[Link to my testes issue](https://try.gitea.io/xoac/capitalX/issues/1)

**Comment by xoac** [comment]
The bug described in the first post and in first comment are different and are not related each other. I am more interested in the first one since it's in stable.

**Comment by zeripath** [comment]
The original issue has already been fixed in master - quite recently I think. If you can find the PR number - it was by me I can I probably backport it.

**Comment by zeripath** [comment]
The original issue was fixed by #10979

**Comment by xoac** [comment]
I don't need backport. I just reported bug. I use gitea myself so I how to deal with it.

Fell free to close it when #11328 will be merged
