### ISSUE TITLE
An internal CI/CD system compatible with Github actions workflow yaml syntax, action yaml syntax and most action plugins

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#13539]
# Internal CI/CD system

I propose to implement an internal CI/CD system that is compatible with Github workflows `yaml` syntax, action `yaml` syntax, and most action plugins. And this is in fact not only a CI/CD system, but you can also choose to not check out the code for some events for example, when an issue is posted, you want to reply to them, then you don't need to check out the code. You can just reply to that issue. So the sub-system name is ~`bots`~`actions`, if you have a better name than that, please let me know.

## Pros

-  Migrated repositories from Github could easily reuse the actions workflow files
-  Plugins could be copied from https://github.com/actions or https://gitea.com/actions to your self-hosted Gitea instances or any git service repository address
-  Transparent for the CI/CD process. You can check out all workflow files and plugin codes you are using.
-  Bring version management for your CI/CD scripts and plugins
-  Customize your image. Github's image for `ubuntu-latest` is very big but Gitea now will use `node:16-buster` as the default image which is about 150MB and of course you could change it yourself.

## Cons

-  Images are maybe very big for those small devices and have to be changed when you have new dependencies.
-  Many Gitea users are familiar with Drone/Woodpecker
-  More feedbacks are welcome

# Reference documentation

At the moment, we lack documents, but if you want to know more details about what Github Actions looks like, please visit https://docs.github.com/en/actions.

# Names chosen

Different from Github's related sub-system's name, we call the plugins `action` or `actions`. One `action` in fact is a repository with a file named `action.yml` in the root, the repository is hosted in any git service server which could be `gitea.com`, your self-hosted Gitea instance, and even github.com. There is a default configuration but we should also support absolute git URL as a plugin repository.

# Task summary

There are many things need to do

- [x] Secrets management #22142  
- [x] An event listener and task scheduler #21937 
- [x] A stable communication protocol between Gitea and runners https://gitea.com/gitea/actions-proto-def
- [x] A runner based on docker https://gitea.com/gitea/act_runner
- [x] A UI that will show tasks and logs #21937 
- [x] Some core actions are now in https://gitea.com/actions which currently are mirrors but may be changed if there are incompatible between Github API v3 and Gitea API v1
- [x] Support absolute plugin address like `uses: https://github.com/peaceiris/actions-hugo@v2` https://gitea.com/gitea/act/pulls/14
- [x] Artifact protocol compatible with Github's, some reports could be displayed in UI directly i.e. Golang standard coverage file #22738
- [x] Service support https://gitea.com/gitea/act/pulls/5
- [x] Cron support #26655
- [x] Cache action https://gitea.com/gitea/act_runner/pulls/25
- [ ] The default plugin programming language is `Javascript/Typescript`, but we need to support more programming languages
    - [ ] `Python` https://gitea.com/gitea/act_runner/issues/44
    - [x]  `Golang`
    - [ ]  `Rust`
    - [ ] `PHP`
    - [ ] More
- [ ] Check tab in the pull request to list results on the pull request page so that we don't need to go to actions page
- [ ] Composite workflow, a workflow file could reference another workflow as a step.

Although we will have an internal CI/CD system Gitea will still be open to integrating external systems and will provide more features to make the integration smooth. The below tasks do not belong to the internal CI/CD system but are very important for integrating the external CI/CD system
- [x] A standard protocol to get tasks and get logs back https://gitea.com/gitea/actions-proto-def

**Comment by a1012112796** [comment]
tips about api for ci tools to repot detail message:

1. lint messages, can show them like code comment (but can marked as wrong by manager)
the stype of data that provide by api
```JSON
{
    commit: xxxxxxx
    path: "xxxxx/xxxxx",
    line: -1,
    type:  bug/ security/ codesmell/ info,
    detail: xxxxxxx,
   provider: xxxxx,
}
```

example in gitee
![image](https://user-images.githubusercontent.com/25342410/99187445-a102f980-2791-11eb-83f6-a970c8ccdcfb.png)

2. code coverage data like codecov
```JSON
{
    commit: xxxxxxx
    path: "xxxxx/xxxxx",
    group: golang,    // only data in same group will be calculate together
   provider: xxxxx,
   start_line: xx,
   start_cols: xx,
   end_line: xx,
  end_cols: xx,
  matched: 0 -- not, .>1 -- yes
}
```

do some calculate and show some usefull data on ui.

3. detal log in ci steps, should show them in an individual page like gh actions.
 then user can design a sample ci tools which not need it's own ui :)
style:
```JSON
{
    commit: xxxxxxx
    step_name: aaa,
    parent_step_name: bbb,
   previous_step_name: ccc,
    log: xxxxx, or link to log data
   status: pending or runing or success ....
}
```

**Comment by Be-ing** [comment]
> Support github actions files and allow external agent to execute the action via Gitea's API and returned result as above results.

Can you clarify what this will entail? Would this mean GitHub Actions could run on a github.com mirror of a repo and the results would appear on a Gitea server?

**Comment by lunny** [comment]
That means Github actions could be running on Gitea(with this CI feature) servers(actually on user's agent, Gitea will only a coordinator and result saver).
Then mirrors/migrations of repositories from github/github enterprise could run the ci directly and no(or small) modification needed.

**Comment by a1012112796** [comment]
see https://docs.github.com/en/rest/reference/checks

**Comment by a1012112796** [comment]
see 
- https://docs.github.com/en/rest/reference/checks
- https://docs.github.com/en/rest/reference/code-scanning

**Comment by moqmar** [comment]
Would this be implemented by explicitly checking for a `.github` directory and sending those repos to the agent automatically on push using something like a global webhook? Because I think it would be great to not limit this to just GitHub Actions, but rather have a "global webhook" for pushes to an agent that can then decide what to do with that push - either using the GitHub Actions definitions, or for example running other CI implementations.

**Comment by lunny** [comment]
@moqmar Global webhooks have been implemented. The issue is to be compatible with actions for those migrations from github.

**Comment by ChristopherHX** [comment]
I have been working on an [external webhook entpoint for github actions self-hosted runners](https://github.com/ChristopherHX/runner.server) to use with my gitea instance or locally on any pc. This is basically a fork of the runner to be able to reuse their code for a missing aspnetcore server. During my tests I was able to use gitea almost like a ghes instance, some actions like `actions/checkout@v2` have had minor incompatibilities with authentication.

I would be glad to see endpoints for CI logs and have an integrated UI. Currently I have a basic react UI to display my logs, added as an external tab to gitea.
<p align="center">
  <img src="https://github.com/ChristopherHX/runner.server/blob/main/src/Runner.Server/webpage1.png?raw=true">
</p>

**Comment by techknowlogick** [comment]
@ChristopherHX whoa! That's amazing!!

**Comment by silverwind** [comment]
Regarding the name: I think "bot(s)" is too confusing with "robot(s)" which are automated user accounts. How about naming it "step(s)"? Most of the terminology that relates to "action(s)" would also apply to "step(s)".

**Comment by lunny** [comment]
> Regarding the name: I think "bot(s)" is too confusing with "robot(s)" which are automated user accounts. How about naming it "step(s)"? Most of the terminology that relates to "action(s)" would also apply to "step(s)".

To different from Github Actions, I don't think we should use actions as name. `Bots` might means `automatical` but not `robot`, I'm not English native speaker and maybe there is a better name for it. This is really not only a CI/CD system, you can do more like below yml file.
```yaml
name: Issue post

on:
  issue_comment:
    types: [created]

jobs:
  comment_created:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://gitea.com/peter-evans/create-or-update-comment
          reactions: '+1'
```

**Comment by xin-u** [comment]
... or named `Build(s)`

**Comment by silverwind** [comment]
>  I'm not English native speaker and maybe there is a better name for it

It's well established even in non-english languages that [bot](https://en.wikipedia.org/wiki/Bot) is a program that impersonates a human.

So we are looking for a word that signifies something being done and that word should ideally double as a noun as well. I'll keep looking. "Build" does qualify but is already occupied in the sense of it meaning to construct software.

**Comment by JakobDev** [comment]
I personal think developing this makes no sense. As said in the start post, there are already working CI systems. It would make more sense to integrate e,.g. Woodpecker directly in Gitea instead of wasting a lot of development resources to develop something that already exists.

**Comment by silverwind** [comment]
How about Task(s) or Job(s)? E.g. signifying a unit of work.

**Comment by lunny** [comment]
> I personal think developing this makes no sense. As said in the start post, there are already working CI systems. It would make more sense to integrate e,.g. Woodpecker directly in Gitea instead of wasting a lot of development resources to develop something that already exists.

They are different systems. Gitea could support both.

**Comment by 6543** [comment]
well before merge we should make **sure** https://github.com/woodpecker-ci/woodpecker/issues/1385 is ready and gitea **do** support both **equally**

**Comment by 6543** [comment]
As I pointed out, I don't like the feature-creep but as long as it is possible to disable it **completely**, I won't block this but also wont focus on fix it either ...

**Comment by MarkusAmshove** [comment]
What about Auteamate? 😋
Contains tea, a friendly mate and suggests automation

**Comment by kmk3** [comment]
Suggestions of boring and obvious names:

* Gitea Automation (looks relatively similar to "GitHub Actions")
* Gitea CI (like GitLab CI and countless others)

**Comment by kmk3** [comment]
Suggestions of more "thematic" names:

* Gitea Infusion (like in tea infusion)
* Gitea Pot

(The first one is probably better for SEO)

**Comment by williamdes** [comment]
> Suggestions of boring and obvious names:
> 
> * Gitea Automation (looks relatively similar to "GitHub Actions")

I would put this one first because the name is easy and stays in mind

> * Gitea CI (like GitLab CI and countless others)

Boring but just perfect for what it is 😄

**Comment by tobiasBora** [comment]
Can't we stick to a vocabulary as close as possible to github's when possible? This would allow a faster transition from people coming from github, and ideally easy migrations. Of course, if they do incompatible things we should get a new name. I prefer the "boring" but descriptive terms like "task" compared to fancy unclear terms.

I agree that it would be awesome to have native gitea integration. But if it takes ressources, I agree it would be good to disable it to run it on low-end devices (I still want gitea to run on my raspberry pi).

**Comment by lunny** [comment]
How about motion which is close to action and short enough.

**Comment by xin-u** [comment]
I just tried it and wrote a note:

https://gist.github.com/xin-u/f459c4805b348595e4981000b75443fe

**Comment by lunny** [comment]
> feature-creep

I don't think it's a `feature-creep`. The issue has been opened for 2 years and I have announced I'm working on that in discord for many times. And I think a PR should be created when it's basically ready but not from the day 1.

And I think Gitea should create a standard protocol and other external CI/CD tools could implement that to reuse Gitea's UI. Not only woodpecker, but also drone/jenkins and others could also implement the protocols to upload logs and etc. But I think that could be a standalone PR after a solid proposal.

**Comment by lafriks** [comment]
Yes would be nice if ui had some kind of abstraction to allow implement other runners inside gitea (something ui wise I started once but had no time to finish)

**Comment by lunny** [comment]
> Yes would be nice if ui had some kind of abstraction to allow implement other runners inside gitea (something ui wise I started once but had no time to finish)
> 
> https://github.com/go-gitea/gitea/compare/main...lafriks-fork:gitea:feat/gitea_builds?expand=1
> 
> This way you would not have to enable it specifically, you would have to just add global/org/user/repo runners and use them

Looks like in your design, every runner type has his protocol and Gitea will implement different protocol for different runners?

**Comment by lunny** [comment]
For the name, I think we can have vote.

We have several choices here(sorry this is not the whole suggested because I think we haven't so many emojis :))

- 🚀 Actions
- 💯 Automate
- ❤️ Motions
- 👍 Bots
- 🎉 Auteamate
- 😄 Builds

**Comment by lafriks** [comment]
> > Yes would be nice if ui had some kind of abstraction to allow implement other runners inside gitea (something ui wise I started once but had no time to finish)
> > https://github.com/go-gitea/gitea/compare/main...lafriks-fork:gitea:feat/gitea_builds?expand=1
> > This way you would not have to enable it specifically, you would have to just add global/org/user/repo runners and use them
> 
> Looks like in your design, every runner type has his protocol and Gitea will implement different protocol for different runners?

yes but with common interface that needs to be implemented (like we have for webhooks)

**Comment by BySempron** [comment]
Is there only going to be one docker runner? Docker isn't the best in all setups, so I think we must have a "bare metal" runner which works without docker.

**Comment by tobiasBora** [comment]
If I can give maybe another application of bare runners proposed by @BySempron, it would be for Nix (actually a gitea-native Nix runner would be also really cool… and maybe even simpler to implement as compiling in nix is just a matter of typing `nix build path-of-repo#name-program`). This makes sense when compiling softwares "packaged" using Nix as Nix already provides a sandbox restricting the scope of the building process. And it also gives for free some sort of cache sharing among build (like if my first software packages a package A, and my second software uses A, when the CI builds A, it will be automatically be available when compiling software B without any need of recompiling software A).

**Comment by eeyrjmr** [comment]
fyi "Actions" already refers to a Gitea UI and thus to name the worker scripts "actions" can raise some ambiguity if someone refers to them.  

![2022-11-30_22-11-1669847491](https://user-images.githubusercontent.com/4564448/204922381-e5bbcfd5-c471-4235-9ebc-90b25ee1082f.jpg)

**Comment by TheBrokenRail** [comment]
Name-wise, what about Teapots, Pots, or Kettles? (You know, because teapot/tea kettle?)

I also like "Sips" which was suggested [on the Discord](https://discord.com/channels/322538954119184384/322910365237248000/1047542245387157594).

**Comment by lunny** [comment]
> @BySempron The fork of gitea I saw didn't include my PR for a native execution environment [nektos/act#1293](https://github.com/nektos/act/pull/1293). I hope that this change will be pulled and made available.

I think we can pull upstream code again in https://gitea.com/gitea/act and maybe you can help to send more PRs to these repositories.

**Comment by lunny** [comment]
> Pots

Ah, right. I think we have to change the menu name if `Actions` win.

**Comment by lunny** [comment]
- 👍 Sips
- ❤️ Pots

**Comment by wolfogre** [comment]
> The fork of gitea I saw didn't include my PR for a native execution environment [nektos/act#1293](https://github.com/nektos/act/pull/1293). I hope that this change will be pulled and made available.

@ChristopherHX It's amazing! The forked act is trying to track the latest release of nektos/act, so I will follow up once a new version including the commit is released.

**Comment by kmk3** [comment]
@lunny Suggestion to the above list:

* :tada: Brews

(It works both as a noun and as a verb, so you could have a `[Brew]` button)

**Comment by wolfogre** [comment]
> @lunny Suggestion to add to the above list:
> 
> * 🎉 Brews
> 
> (It works both as a noun and as a verb, so you could have a `[Brew]` button)

Excuse me, don't do that, please! 😂 I'm a user of [homebrew](https://brew.sh/), and typing `brew install ... brew upgrade ...` everyday.

**Comment by kmk3** [comment]
> @kmk3 Excuse me, don't do that, please! joy I'm a user of
> [homebrew](https://brew.sh/), and typing `brew install ... brew upgrade ...`
> everyday.

Ah yes, maybe the CLI usage could be different then, like `tea brew`, `gtb` or
something (in which case the binary name for "Gitea Actions" could be rather
amusing).

Though would there even be a dedicated binary for this?

**Comment by lafriks** [comment]
I think naming should be kept in UI as generic as possible to be able to integrate under that other CI information under it so imho Workflows would be generic enough not to hint to any exact product but be recognizable enough. CI/CD tool that is being developed as one of integration can be named than in some more specific name.

**Comment by wolfogre** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/9418365/205548586-b5a20a67-e31c-44b7-80eb-0a71544560d4.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/9418365/205548652-2170acd9-7384-4d19-a888-b9e16e29e777.png">

I believe `Actions` is the final result. I know it's not perfect, but it's probably good enough for now.

**Comment by gnat** [comment]
Just rename the existing button to Manage (or whatever) and use Actions for this.

**Comment by gnat** [comment]
Wanted to say, as someone who uses a ton of Drone, it's going to be amazing to migrate to this new system and standardize on the Github actions format instead. Really looking forward to this.

**Comment by ibotty** [comment]
As mentioned before, I'd really like to see different runners than only ones based on docker.  There is a reason that the whole red hat influenced world moved away from docker.

But more importantly, I'd like to have a runner that runs the containers in a Kubernetes cluster.  Will it be possible to use a different runner or is there tight integration?  Is there some preliminary documentation besides the source on the api contract between gitea and the actions runner?

**Comment by lunny** [comment]
> As mentioned before, I'd really like to see different runners than only ones based on docker. There is a reason that the whole red hat influenced world moved away from docker.
> 
> But more importantly, I'd like to have a runner that runs the containers in a Kubernetes cluster. Will it be possible to use a different runner or is there tight integration? Is there some preliminary documentation besides the source on the api contract between gitea and the actions runner?

The protocol repository is https://gitea.com/gitea/actions-proto-def. I think we can have more runners in future, but let's have one at first. A runner based on `act` should be the easiest way to make one.

**Comment by sschuberth** [comment]
> Cache action

I guess support for that would require to address https://github.com/nektos/act/issues/989#issuecomment-1156768547, which would be a great step towards running actions that leverage caches locally.

**Comment by yekanchi** [comment]
Great Job, 
I feel most of the people using Gitea over Gitlab and Github enterprise use it because it does not need Linux/WSL/docker stuff.
Then I think  actions runner being native is crucial for real cross platform support.

**Comment by kolaente** [comment]
> I don't have the numbers, but why would anyone run Gitea on Windows instead of a server OS like Linux? I know it can run on Windows, but especially if you allow outside access you don't want a Windows machine connected to the "evil" internet.

There's software you can only build on windows, like tauri (at least for now). I have worked on a project where you could only deploy the software by pushing it to a server in the client's internal network and the vpn they were using was only available on Windows. With a Windows runner it's possible to build pipelines for these use cases which otherwise would be not possible.

**Comment by MrHaroldA** [comment]
Ah, Windows native runners and not "Gitea on Windows"; didn't think about that ;)

Carry on!

**Comment by jmg2k** [comment]
> but why would anyone run Gitea on Windows instead of a server OS like Linux?

Guess you've never heard about Windows Server then and probably also don't know how much easier it is to find administrators who know what they're doing.

**Comment by yekanchi** [comment]
> > Great Job, I feel most of the people using Gitea over Gitlab and Github enterprise use it because it does not need Linux/WSL/docker stuff. Then I think actions runner being native is crucial for real cross platform support.
> 
> I don't have the numbers, but why would anyone run Gitea on Windows instead of a server OS like Linux? I know it _can_ run on Windows, but especially if you allow outside access you don't want a Windows machine connected to the "evil" internet.
> 
> Then again, I can understand the need for native runners for those who haven't containerized their services yet.

Linux servers are more popular over Windows server on the internet but there are many Enterprise Environments  that reply on Active Directory stuff and and use Windows Servers, By the way my purpose was that among Gitea/Github/Gitlab, The Gitea is the only one support Deploying to Windows Servers. so all individuals or companies  who stick with windows have no option but Gitea.

**Comment by techknowlogick** [comment]
@ChristopherHX those are very good points. To confirm, your suggestion is to treat anything that doesn't start with http/s as relative plugin to the default action url, but if it starts with http/s then use absolute? As I think that is a very reasonable suggestion.

**Comment by ragnaros2046** [comment]
Will Gitea CI support buildpacks? [https://buildpacks.io/](url) 

Cloud Native Buildpacks
transform your application source code into images that can run on any cloud.

**Comment by genofire** [comment]
Why was not used the protocol between gitlab and there runner? this runner could be runned everywhere and start jobs in virtualbox, shell, kubernetes, docker ....

**Comment by wolfogre** [comment]
> Why was not used the protocol between gitlab and there runner? this runner could be runned everywhere and start jobs in virtualbox, shell, kubernetes, docker ....

GitLab runners are designed for [.gitlab-ci.yml](https://docs.gitlab.com/ee/ci/yaml/), however, what Gitea wants is [Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions).

**Comment by genofire** [comment]
But for Actions does not exists an good runner, with `service`, running in kubernetes and so on.
Why has gitea the same API then github?

**Comment by dorianim** [comment]
Oh, I see. Yes, you're probably right about that. The color code validator shouldn't be needed anywhere else. I'll move it.

**Comment by lunny** [comment]
> Why was not used the protocol between gitlab and there runner? this runner could be runned everywhere and start jobs in virtualbox, shell, kubernetes, docker ....

I think we can discuss the possibility of whether we can support that protocol and GitLab runners.

**Comment by newbenji** [comment]
but you still need build it yourself to test it?

**Comment by balki** [comment]
For a mirror repository, Will it be possible to use different action instead of the one in the original repository?

For example, lets say the github action in https://github.com/go-gitea/gitea compiles gitea when a new tag is created with `TAGS="bindata sqlite sqlite_unlock_notify" make build`. 

I set up a mirror repository at https://git.mydomain.com/me/gitea and in my gitea action, I would like to it to compile without sqlite support, `TAGS="bindata" make build`.

For this to work, the config cannot be inside `.github` or `.gitea` folder as that will cause conflict with original repository. Instead, we can have in a custom branch called `.gitea-actions-branch` which only contains the yaml config file for 'gitea action'.

**Comment by douglasparker** [comment]
> For this to work, the config cannot be inside `.github` or `.gitea` folder as that will cause conflict with original repository. Instead, we can have in a custom branch called `.gitea-actions-branch` which only contains the yaml config file for 'gitea action'. 

I think it would be nice to be able to select which folder to use for Gitea Actions via a global and project level flag, with the project level flag taking priority.

That way Gitea Actions can ignore the .github folder in favor of the .gitea folder.

**Comment by panekj** [comment]
You can't modify files in mirrored repository.

> For this to work, the config cannot be inside `.github` or `.gitea` folder as that will cause conflict with original repository. Instead, we can have in a custom branch called `.gitea-actions-branch` which only contains the yaml config file for 'gitea action'.

It will be better to have a event hook that will trigger actions in another repository, so mirror would trigger a hook, that hook triggers an actions run in another repository which will allow you to specify whatever you want.

**Comment by nodiscc** [comment]
Gitea [1.19.0](https://github.com/go-gitea/gitea/releases/tag/v1.19.0) was released with the initial actions implementation, but I do not see any mention of it at https://docs.gitea.io/. So maybe a new task should be added to the checklist in the issue description?

- Document Gitea actions setup and configuration

**Comment by wizpresso-steve-cy-fan** [comment]
It is also well noted we will also need to add Helm chart for act

**Comment by kbingham** [comment]
> For this to work, the config cannot be inside `.github` or `.gitea` folder as that will cause conflict with original repository. Instead, we can have in a custom branch called `.gitea-actions-branch` which only contains the yaml config file for 'gitea action'.

Being able to store the configuration in a custom branch would help a lot for adding automation to open source projects that don't want to have specific CI files added to the core repo. The linux kernel for instance.

**Comment by lunny** [comment]
> > For this to work, the config cannot be inside `.github` or `.gitea` folder as that will cause conflict with original repository. Instead, we can have in a custom branch called `.gitea-actions-branch` which only contains the yaml config file for 'gitea action'.
> 
> Being able to store the configuration in a custom branch would help a lot for adding automation to open source projects that don't want to have specific CI files added to the core repo. The linux kernel for instance.

Maybe we can have some options:
1) `.github/workflows` or `.gitea/workflows`
2) <repo_name>.actions.git like <repo_name>.wiki.git
3) A setting of the repository to store multiple workflow files.
4) A global workflows feature, which you can create a workflow to includes files and repositories.

**Comment by kbingham** [comment]
Yup now I've been exploring more, I can see a separated repo for the workflows could be a very helpful way of doing this too. Then multiple repos (mirrors, forks, or separate repos for separate developers) can point to common workflow actions.

**Comment by sh7dm** [comment]
Maybe after artifact upload is done, basic code intelligence (not as powerful as SourceGraph, but just goto definitions/references + browse file symbols) could be implemented. After finishing builds/tests the action might do something like `rust-analyzer lsif .` and upload it as a special artifact Gitea will build navigation from. This approach gives the most detailed code navigation, just as in IDE using the same language server as used to generate LSIF. See https://lsif.dev/ for more details regarding the format.

Didn't open a new issue because of dependency on artifacts

**Comment by prologic** [comment]
Are there any docs on built-in actions in 1.19.0? Even just a quick bullet point here in this thread? 🙏

**Comment by prologic** [comment]
Answering my own question, getting this up and running with Gitea v1.19.0 (from upstream Docker images) was pretty straight forward:

1. Add the following to your `app.ini` config (since if you're running an older version, it won't be there by default and disable by default?):

```ini
[actions]
ENABLED = true
```

2. Restart Gitea
3. Go to Site Administration -> Runners
4. Create new Runner and Copy the token
5. Setup and register a Runner

```console
$ git clone https://gitea.com/gitea/act_runner.git
$ cd act_runner
$ make build
$ ./act_runner register
# follow the instructions
$ ./act_runner daemon
```

That's it! 🥳 Now just add workflows in `.gitea/workflows/build.yml` which use the same syntax as Github actions? (I guess so since the runner being used is the `act_runner`).

**Comment by prologic** [comment]
Happy to continue beta testing this (I also run an older Drone CI setup too!) and provide feedback.

One thing that springs to mind (which I'm hoping one of the developers can answer):

- How do I set-up Gitea + actions in a way where I can spawn runners on demand? (like Github does)

Basically, instead of having a static pool of runners (however I choose to run them), it would be nice to have a webhook (globally) that I can listen on and spawn a new runner on demand (say in a virtual machine or similar). Thanks! 🙏

**Comment by jimafisk** [comment]
I think it's just:
```
[actions]
ENABLED = true
```
https://docs.gitea.io/en-us/config-cheat-sheet/#actions-actions

**Comment by delvh** [comment]
No, the cheatsheet is still true.
You simply misunderstood something here: the key `DEFAULT_REPO_UNITS`/`DEFAULT_FORK_REPO_UNITS` [[repository]](https://docs.gitea.io/en-us/config-cheat-sheet/#repository-repository) used the key `actions` instead of `repo.actions`.
The section to enable actions is [[actions]]https://docs.gitea.io/en-us/config-cheat-sheet/#actions-actions).

**Comment by lunny** [comment]
All units configuration should use `repo.actions`, but the ini section is `[actions]`.

**Comment by RynoM** [comment]
> * How do I set-up Gitea + actions in a way where I can spawn runners on demand? (like Github does)

This would be nice! I've been [tinkering with using it](https://github.com/RynoM/self-hosted-deployment) to deploy/restart my docker services. Would be nice if it could just do dynamic generation / access from outside for runner tokens. That way the container is more ephemeral.

Also its probably been said before, but an environment variable for enabling actions would be nice, instead of having to update `app.ini`.

**Comment by panekj** [comment]
> I have setup the runner and everything and I have a `docker build` command to run in my action. Unfortunately I get `/var/run/act/workflow/1: line 2: docker: command not found`. Anyone knows the best way to enable docker inside the runner?

You need to install it or use a docker image runner that has it installed

**Comment by sorenisanerd** [comment]
Another missing part of Gitea's implementation of Github Actions is workflow commands in general, but most critically the `add-mask` command. My logs are riddled with secrets that anyone can see and steal.

**Comment by prologic** [comment]
> Another missing part of Gitea's implementation of Github Actions is workflow commands in general, but most critically the `add-mask` command. My logs are riddled with secrets that anyone can see and steal. 

Wait?! Why are you logging secrets in the first place? 🤔

**Comment by vquie** [comment]
> Another missing part of Gitea's implementation of Github Actions is workflow commands in general, but most critically the `add-mask` command. My logs are riddled with secrets that anyone can see and steal.

I can confirm this. I use the 1password action to retrieve passwords. They are logged in all their beauty. Their code says `add-mask` though.

**Comment by JakobDev** [comment]
> Wait?! Why are you logging secrets in the first place?

There are Programs who print API Keys for debug reasons with no Way to disable it. It also possible, that this may be leaked in a error message when something crashes, so it's generally a good Idea to mask this, just in case.

**Comment by kbingham** [comment]
> Yup now I've been exploring more, I can see a separated repo for the workflows could be a very helpful way of doing this too. Then multiple repos (mirrors, forks, or separate repos for separate developers) can point to common workflow actions.

FWIW - Today I discovered gitlab can do this and it's all documented here: 
 - https://docs.gitlab.com/ee/ci/pipelines/settings.html#specify-a-custom-cicd-configuration-file
 - https://gitlab.com/gitlab-org/gitlab/-/issues/14376

**Comment by prologic** [comment]
> > Wait?! Why are you logging secrets in the first place?
> 
> 
> 
> There are Programs who print API Keys for debug reasons with no Way to disable it. It also possible, that this may be leaked in a error message when something crashes, so it's generally a good Idea to mask this, just in case.

Those programs should be loaded up on a rocket and shot into sun! 😆 talk about security law practice 🤦‍♂️

**Comment by delvh** [comment]
I wonder how much more we want to abuse this one issue?
As far as I'm concerned the basic functionality exists, and the remains should be extracted into separate issues.
I don't think it's good that this issue is still open despite the main functionality being implemented already.
Issues should focus on one specific thing, otherwise they'll be pretty much never closed.
