### ISSUE TITLE
Mirror Summary

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14608]
* [x] ~~Mirror issues along with the repo #1876~~
* [ ] Mirror new-created wiki when repositories migrated #2309
* [x] Reverse mirroring, from Gitea to remote Github/Gitlab/Gitea and etc. #3480
* [ ] Mirror repositories could not be readonly and Allow to push commits manually #7609
* [ ] Mirror an entire github organization into gitea organization #8424
* [ ] Mirror Topics #14590
* [ ] Mirror Docs

**Comment by c4lliope** [comment]
I searched for "Mirror" on https://docs.gitea.io, and I didn't see much describing how mirrors run;
e.g. what happens automatically (`git pull`, `git prune` from the origin codebase?)
and what must be updated by a manual process (issues, wiki pages).

Someone visiting `gitea.com` as an end user will probably need a summary page
of the purpose and mechanisms of mirror repositories.
Maybe a paragraph on the "import repository" page could help people learn more.

**Comment by kdumontnu** [comment]
Is https://github.com/go-gitea/gitea/issues/3480 a duplicate issue to https://github.com/go-gitea/gitea/issues/7609?

**Comment by lunny** [comment]
@kdumontnu I think it's not the same. #3480 means a reverse mirror, #7609 means a mirror repository could be not readonly.

**Comment by lunny** [comment]
> I searched for "Mirror" on https://docs.gitea.io, and I didn't see much describing how mirrors run;
> e.g. what happens automatically (`git pull`, `git prune` from the origin codebase?)
> and what must be updated by a manual process (issues, wiki pages).
> 
> Someone visiting `gitea.com` as an end user will probably need a summary page
> of the purpose and mechanisms of mirror repositories.
> Maybe a paragraph on the "import repository" page could help people learn more.

Yes, mirror docs is also needed.

**Comment by kdumontnu** [comment]
@lunny thx, but the syntax is very confusing then. You say "Reverse mirroring #7609" above, but "#3480 means reverse mirror". 

Do you mean then: "Enable pushing to Gitea repo configured as secondary mirror #7609"?
And "Enable Gitea as primary in mirror configuration #3480"?

We can use consistent diction for mirrors as "primary (push)" and "secondary (pull)"

---

Also, I added a bounty to #3480 if you can add the following:
```
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=54827645)](https://www.bountysource.com/issues/54827645-ability-to-automatically-push-to-remote-mirror-repository)
```
- Enable Gitea as primary in mirror configuration #3480 [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=54827645)](https://www.bountysource.com/issues/54827645-ability-to-automatically-push-to-remote-mirror-repository)

**Comment by lunny** [comment]
> @lunny thx, but the syntax is very confusing then. You say "Reverse mirroring #7609" above, but "#3480 means reverse mirror".
> 
> Do you mean then: "Enable pushing to Gitea repo configured as secondary mirror #7609"?
> And "Enable Gitea as primary in mirror configuration #3480"?
> 
> We can use consistent diction for mirrors as "primary (push)" and "secondary (pull)"
> 
> Also, I added a bounty to #3480 if you can add the following:
> 
> ```
> [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=54827645)](https://www.bountysource.com/issues/54827645-ability-to-automatically-push-to-remote-mirror-repository)
> ```
> 
> * Enable Gitea as primary in mirror configuration #3480 [![Bountysource](https://camo.githubusercontent.com/201b3d010d481c895733bcec38918445b78cbdd27c8a720ead1e80ba63029d22/68747470733a2f2f6170692e626f756e7479736f757263652e636f6d2f62616467652f69737375653f69737375655f69643d3534383237363435)](https://www.bountysource.com/issues/54827645-ability-to-automatically-push-to-remote-mirror-repository)

Thanks, I have updated the issue content. I haven't followed your advise because I think `primary` and `secondary` is still confusing. Please let me know if you think it's still confusing. :)

**Comment by 6543** [comment]
Option to "protect" mirrors (dont sync if it will drop commits or is a completly new history)

**Comment by a1012112796** [comment]
suggest add gitee.com support, from  #15945

**Comment by 6543** [comment]
@a1012112796 wrong summary issue :)

Do you mean  #8689?

**Comment by Sirttas** [comment]
I would suggest in addition to the issue #3480 to add the ability to only push certain branch, tags, etc.

**Comment by culmat** [comment]
see also #18220

**Comment by zc-devs** [comment]
> ability to only push certain branch, tags, etc

I order to prevent [deleted or force-pushed commits from appearing in the GitHub Activity](https://github.com/orgs/community/discussions/53140#discussioncomment-6052248)(and [again](https://github.com/orgs/community/discussions/123659)), it would be nice to have some threshold on commit age when scheduled push mirror is enabled. Like once per a day push the only commits (tags, etc.), which older than 8 hours, for example.
