### ISSUE TITLE
Projects Summary

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14710]
## Naming

- [x] Kanban "board" naming is misleading #13802 #20985
- [x] ~#14679~

## Usability

- [x] Drag sorting for board issues #13805 (#14634)
- [x] Colored boards #11160 (#16647)
- [x] Save order of issues on boards #11161 (#17152)
- [x] "new issue" button in project view #14824
- [x] Organization-level projects #13405 (#22235)
- [x] Filter issues by project #14298 (#22544) 
- [ ] Automated project board #14359
- [ ] Default Project #14871
- [ ] https://github.com/go-gitea/gitea/issues/28161

## API

- [ ] [FEATURE] API for projects #14299

## Advanced Scrum Features / Future Enhancements

- [ ] Multiple projects per issue #12974
- [ ] Swimlanes on kanban boards #14670
- [ ] Kanban board notes #12513

**Comment by delvh** [comment]
#14709 can be removed as it is already fulfilled (project board order is implemented (#14634) and all other mentioned requests are listed here).

**Comment by lonix1** [comment]
Also swimlanes #14670

**Comment by skipperTux** [comment]
1. Create tasks (~ issues) from Kanban board.
Seems like creating entries for a board can only be done via creating an issue and assign the issue to a project. Then the issue is shown in the board in column Uncategorized.
2. Issues are only loosely linked to a column.
Closing an issue does not move the issue to any other column (like 'Done'), it just turns red. Also moving an issue between columns does not change the issue status, like started, in progress or closed. Of course no semantic is currently defined for columns. Define which column is for 'in progress', which column is for 'done/closed', via name or else.

**Comment by delvh** [comment]
@skipperTux
for 1: see #14824 (partially related)
for 2: see #14359

**Comment by skipperTux** [comment]
I thought this is the summary issue where Kanban ideas are consolidated. But I should have linked to those issues for reference. Sorry and thanks.

**Comment by schorsch13** [comment]
I think one point is missing on the list. You are currently not able to change the order of issue within a board. They are always sorted by the issue number descending

**Comment by delvh** [comment]
> I think one point is missing on the list. You are currently not able to change the order of issue within a board. They are always sorted by the issue number descending

>  [x] KanBan: Save Order Of Issues on Boards #11161

Isn't this already implemented with #17152?

**Comment by Extarys** [comment]
I believe you can check `Kanban: Support for organization-level boards` from the list as both PR are merged. :)

**Comment by KiaraGrouwstra** [comment]
- #20988
- #24179
- #24180
