### ISSUE TITLE
Signing Summary

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#14736]
- [ ] use keyserver #9732
- [ ] explain how/where to add GPG within official Docker container #10682
- [ ] Remove GPG binary deps #13367
- [ ] GPG Signing: let user provide signature #9723
- [ ] GPG support for signing tags #4137
- [ ] GPG Signing: more expressive settings #9722
- [ ] Signing with server gpg key but with committer's name and email #14735
- [ ] Signing Key Interface For External Keys #13391

**Comment by KN4CK3R** [comment]
We already have `github.com/keybase/go-crypto/openpgp`.
