### ISSUE TITLE
Branches/Tags Protection

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#15548]
This is a summary issue to track all branches/tags protection related issues

- [x] Wildcard Protected Branch #2529 resolved by #20825
- [ ] Allow the ability to reject force pushes to branches with an open pull request #12011
- [x] Feature Request: Protect tags #15545
- [x] Make Protected Branches -> Approvals section easier to understand #8407
- [x] When there is no branch protected, the reviews of those who have code write permission should be consider as official #10624
- [ ] #20822
- [ ] Add an option to disallow commiters to approve pull request #7072

**Comment by KN4CK3R** [comment]
- [ ] Branch Protection Impossible For New Repositories #15705
