### ISSUE TITLE
Tracking issue: Updating golangci-lint

### ISSUE THREAD

**Issue by Gusted** [go-gitea/gitea#17596]
This is a tracking-issue to update golangci-lint to a newer version - this is just to track which errors has to be fixed that comes up with the newer version of golangci-lint, v1.43.0.
The new update seems to catch more errors, which is always nice to have.

- [x]  Somehow update the existing installs of golangci-lint with e.g. gitea CI, otherwise it will be continue using v1.37.0 (#17647)
- [x] Fix the errors that present with the newer version of golangci-lint.
  - [x] SA4023 errors from staticcheck (#17598)
  - [x] offBy1 errors from gocritic (#17606)
  - [x] badCall errors from gocritic (#17608)
- [x] Update Makefile to download the newer version by default (#17647)
- [x] Remove `golint` as linter, as it's been [deprecated](https://github.com/golangci/golangci-lint/pull/1965) (#17609)
- [x] Check if we can add new added linters (#17610)

**Comment by wxiaoguang** [comment]
(The issue was close by PR merging automatically, reopen it. How to prevent the issue from being closed automatically?)

**Comment by Gusted** [comment]
> (The issue was closed by PR merging automatically, reopen it. How to prevent the issue from being closed automatically?)

Not really, when using closing keywords on github, they will just happen. On the PRs I've on purpose add a little spelling mistake so it wont be recognized as closing keyword, this one got slipped trough.

**Comment by Gusted** [comment]
Closing
