### ISSUE TITLE
[Feature Request] Analytics

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18262]
# Main idea

I was thinking about how to improve gitea so it can better compete with the other mainstream git hosting platforms. I discovered that both GitHub and GitLab have pretty good analytics for profiles and repos. 

# Comparison to other platforms

While gitea only has a contribution heatmap for profiles and only a counter for issues and PRs for repos, GitHub has a pretty awesome overview of all different types of contributions you did

![image](https://user-images.githubusercontent.com/97637661/149400419-55dc423e-1a3f-4230-b734-f897ef7a51db.png)

for profiles and for repos it has an overview of:

- [x] 1. contributors and how many contributions they have done over time #27882 

![image](https://user-images.githubusercontent.com/97637661/149400734-5a67e7bd-af1d-4591-a3ff-ea9b272ac703.png)

- [x] 2. commits over time #29210

![image](https://user-images.githubusercontent.com/97637661/149400838-3e0defb0-f4f3-4f37-9734-b89384761bde.png)

- [x] 3. additions and deletions over time #29191 

![image](https://user-images.githubusercontent.com/97637661/149400921-716483b6-4aca-4160-8a86-187f0b82c699.png)

GitLab on the other hand has similar features on profile analytics but for repos, oh boy, there are the most awesome analytics you can have for a repo. Listing the best ones:

1. Commits over time where you can filter for branches

![image](https://user-images.githubusercontent.com/97637661/149405483-e538d6e4-3a23-48cf-b9ab-5537035683d9.png)

2. Issues over time

![image](https://user-images.githubusercontent.com/97637661/149401555-ced1d099-36f6-4dfe-9502-8e6f0a824205.png)

3. PR stats

![image](https://user-images.githubusercontent.com/97637661/149401657-3cfec8ac-9bfd-442b-b3c0-a004b6a6b774.png)

4. The different stages of new features. From when the issue is created to when the PR is merged. How much time does a feature spend in which state. (pretty useful to improve your deployment rate)

![image](https://user-images.githubusercontent.com/97637661/149401880-a66c2226-c033-4b0c-a22c-23b2d8a8fb0b.png)

Gitea is my favourite alternative to all the proprietary and open-core git hosting platforms out there and I use it for all my projects but there is a long way ahead for gitea to become a good alternative from a business pov. Teams need more tools to collaborate and a analytics system would definitely be a good selling point.

# Suggestions

- Profile
    - A graph to show what your contributions actually are (50% Code Review, 25% Commits, 15% Issues, 10% PRs).
    - All-time stats (Total number of commits: 1,7k, PRs: 146, Languages used: 57% Java, 15% C++. etc.)
    - A drop down menu to select the year to show in the contribution heatmap
    - For further ideas have a look into this awesome looking gh profile https://github.com/marcosbarker
- Repositories
    - Commit statistics
        - Commits over time (per Year/Month/Day of the month/Day of the Week/Hour)
        - Amount of commits per user
    - Issue statistics
        - Issues created and closed over time (per Year/Month/Day of the month/Day of the Week/Hour)
    - PR statistics
        - PRs created and closed over time (per Year/Month/Day of the month/Day of the Week/Hour)
        - List of PRs with following stats (maybe also graphical):
            - Additons/Deletions
            - Time from opening to closing
            - Number of Contributors/Reviewers
            - Number of Commits
            - Number of Comments
    - [OPTIONAL] Feature Life Cycle: From the creation of an issue over the commits on a related branch to a PR until it has merged. In which state does a feature last how much time (where would I need to improve to get faster deployments)

# Remark

I know that this feature is beyond the scope of an issues. It is rather an entire Milestone but since I am just a user of gitea and not a team member I thought creating an issue would be the right way to start.

Also I would be interested in helping with the development of this system but I thought it would be better to first ask for feedback before I just start implementing my ideas.

Therefore, feel free to share your opinion to help improving gitea.

**Comment by vhscom** [comment]
I feel a good first step would be to get a download count displayed so users can add a badge to their repos. Then this feature could be iterated on so that more detailed (and privacy-conscious) analytics put in place as time goes on. The single step of adding a download counter would give maintainers a better feel for which apps to spend time on and end-users more transparency over the popularity of a project without relying on star count (in turn giving users a reason to sign-up for an account). Somethig like fail2ban could be used to prevent gaming the download counts.

**Comment by schorsch13** [comment]
I totally agree. A download counter for releases is very important and would be a great addition to gitea

**Comment by kap-jyahn22** [comment]
totally agree

**Comment by kurotanshi** [comment]
+1 on this. I'd like to add a concrete use case that the existing repo-level features don't cover.

As an admin of a self-hosted instance, one of the most common things I need is a per-user contribution overview that spans all 
repositories, so I can do monthly/quarterly team reviews. Today this is surprisingly hard in Gitea:

- The profile activity tab only gives a heatmap + a raw activity feed — no breakdown by contribution type.
- The repo Activity / Contributors graph (#847) is great, but it's scoped to a single repo and only counts commits. In a setup with
dozens of repos, I can't get a per-person picture without manually visiting every repo.

What's missing is essentially what GitHub shows on a profile:

- A contribution breakdown by type (Commits / Pull requests / Issues / Code reviews) as proportions, not just a heatmap.
- Aggregated across all repos the user can see, for an arbitrary date range (e.g. a quarter), not just fixed periods.
- Ideally comparable across multiple users for team reporting.

The Code review dimension is especially valuable and currently invisible anywhere in the UI — reviewing others' PRs is real work, and
right now there's no way to see who is carrying the review load.

I ended up scripting this against GET /users/{username}/activities/feeds?only-performed-by=true, aggregating op_type into those four
buckets. It works, which suggests the data is already there — it just isn't surfaced in the UI. Even a read-only profile panel (or an
admin-only report) built on the existing activity data would go a long way.

Would the maintainers be open to this, perhaps as an extension of the contributor-stats work in #37209?
