### ISSUE TITLE
Enhancements of webhooks

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#3998]
- [ ] Custom Webhook Templates Issue(#1089)
- [x] Webhook for mirrored repositories Issue(#1002 implemented in #4127)
- [x] Allow adding a default set of githooks and webhooks Issue(#770)
- [x] Add more event types to get parity with GitHub event types (#2113)
- [x] branch filter for push/pull request notifications  Issue(#2025) Open
- [x] Resend webhook payloads (#4589)
- [x] https://github.com/go-gitea/gitea/issues/9485

**Comment by lunny** [comment]
This is an enhancement of #2418

**Comment by noplanman** [comment]
Would be great if it were possible to resend a webhook payload.
It sometimes happens that a webhook call times out, so just being able to kick it again would be super helpful.

Is there a way to do this as it is now?

**Comment by lunny** [comment]
@noplanman I think there is not. You can fire another issue and I can reference that issue here since this is only a summary issue.

**Comment by noplanman** [comment]
@lunny Will do, thanks!

**Comment by SystemZ** [comment]
Probably related as docs are not complete regarding webhooks: https://github.com/go-gitea/gitea/issues/9485
