### ISSUE TITLE
All LFS files got empty (no more Stored with Git LFS) after Gitea WebUI file editing and commit

### ISSUE THREAD

**Issue by lanterna72** [go-gitea/gitea#4778]
- Gitea version (or commit ref): 1.5
- Git version: 2.18.0
- Operating system: Windows Server 2016 Standard
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] MSSQL (SqlServer 2016 Standard Edition)
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No   (because gitlfs is not enabled)
  - [ ] Not relevant
- Log gist:

*config file* has gitlfs enabled
```terminal
...
LFS_START_SERVER = true
LFS_CONTENT_PATH = C:/gitea/data/lfs
LFS_JWT_SECRET = <<token>>
...
```

### Phase 1 - 1st commit
I do have a project with a markdown file in the root folder and a folder named 'lfs_files' where there are .png and .pdf files. 

before 1st commit I enabled LFS and tracked png and pdf files as in the git lfs tutorial https://git-lfs.github.com

```terminal
git lfs track "*.pdf"
git lfs track "*.png"
git add .gitattributes
```

I do the 1st commit and 1st pull, all ok, accessing the WebUI I see all files are committed and all LFS tracked files reports the correct size and label *(Stored with Git LFS)*

![image](https://user-images.githubusercontent.com/1898670/44553128-d3e1f280-a72c-11e8-85ea-be2cd639dcbb.png)

![image](https://user-images.githubusercontent.com/1898670/44553146-e0fee180-a72c-11e8-9c78-f65efbb4974a.png)

### Phase 2 - Edit markdown file under gitea webui

I edit the index.md directly in the gitea webui and commit clicking on **commit changes** button

![image](https://user-images.githubusercontent.com/1898670/44553342-6bdfdc00-a72d-11e8-9af7-8563859b0366.png)

From now on all LFS files has 0 size and *(Stored with Git LFS)* is disappeared.

![image](https://user-images.githubusercontent.com/1898670/44553403-a6e20f80-a72d-11e8-9963-e45a4106077f.png)

I tried with multiple repositories, simple or more complex all led to the same result.
