### ISSUE TITLE
[Branch View] some enhancements

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7454]
# Tasks
## Add info & Functions
* [x] commit id & commit message (https://github.com/go-gitea/gitea/pull/7461)
* [x] if it's protected (https://github.com/go-gitea/gitea/pull/7461)
* [x] if it's default (https://github.com/go-gitea/gitea/pull/7461)
* [x] download (https://github.com/go-gitea/gitea/pull/7604)
* [x] Indicade if it is merged manualy ~~(https://github.com/go-gitea/gitea/issues/7976)~~ (https://github.com/go-gitea/gitea/pull/8449)
## related bugs
* [ ] ~~fix restore button (https://github.com/go-gitea/gitea/issues/7569)~~
* [x] fix  inconsistent protected symbol (https://github.com/go-gitea/gitea/issues/7576)
* [x] User wit RO rights can't see protected lable (https://github.com/go-gitea/gitea/issues/7577)
* [x] del dublicate protect icon (https://github.com/go-gitea/gitea/pull/7624)
* [x] commit divergence is wrong shown at smal size (https://github.com/go-gitea/gitea/issues/7625)
* [x] del button should be hidden on an archived repository (https://github.com/go-gitea/gitea/issues/7653)
## Improvements
* [ ] ~~put all controll buttons in the same `td` and make them look similar (https://github.com/go-gitea/gitea/issues/7606)~~
* [x] don't show "New Pull Request" Button if there is nothing to merge (https://github.com/go-gitea/gitea/issues/7975)
* [x] remove table Header of branches (https://github.com/go-gitea/gitea/pull/7622)

**Comment by 6543** [comment]
perhaps the other information is alo usefull (the tags, the commits behind/ahead) ...

**Comment by lunny** [comment]
This has been merged in #6990

**Comment by lunny** [comment]
Something are absent.
- [ ] commit id & commit message
- [ ] time
- [ ] if it's protected
- [ ] download

**Comment by 6543** [comment]
@lunny #6990 would resolve my needs - i searched for it but didn't found it - sory

> Something are absent ... 
shoud we rename the issue to specify it?

**Comment by lunny** [comment]
@6543 title changed

**Comment by gary-kim** [comment]
Sounds like a good idea. I'll see if I can work on this.

**Comment by lunny** [comment]
@gary-kim Oh. yes, time is already there.

**Comment by lunny** [comment]
Commit message break. I think maybe you should reuse the commit message code on commits page or repo home page.

![image](https://user-images.githubusercontent.com/81045/61181610-81b70200-a65b-11e9-98c8-d659a31813ff.png)
![image](https://user-images.githubusercontent.com/81045/61181616-8976a680-a65b-11e9-854d-2348b40747fa.png)

**Comment by 6543** [comment]
@gary-kim thanks! update issue

**Comment by 6543** [comment]
what do you think should it say merged when latest commit is in **some** other branch or if it is in **default** one?

**Comment by lunny** [comment]
partially fixed by #7461

**Comment by lunny** [comment]
@6543 merged to which branch?

**Comment by 6543** [comment]
if you have many branches ... and the last commit(hash) is in the default branch .. you can delet it without having to wory about losing something ... - that's what i like to use it for

I'll test the #7461 after my exams ... sory i'll have less time

**Comment by 6543** [comment]
-> ned som help with css (menue changes colum or is hidden)

style="position:relative;" / tyle="position:absolute;"

**Comment by lunny** [comment]
@6543 If a repository use pull request, the merged label is unusable. But for others with no pull request, merged label is very usable. I will find time to review your PR.

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/pull/7520 is now ready to review

**Comment by 6543** [comment]
#7566 how to tell people when branch realy is deleted

**Comment by 6543** [comment]
Current State: https://github.com/go-gitea/gitea/pull/7520#issuecomment-513991651

**Comment by 6543** [comment]
@lunny @gary-kim what do you think of PR 7520 curent state?

**Comment by lunny** [comment]
@6543 I have gave that L-G-T-M

**Comment by 6543** [comment]
> @6543 I have gave that L-G-T-M
i split the PR to get things that are right merged and work only on things wich need improvement - I'm sorry to bother you with this.

**Comment by 6543** [comment]
updated tasks list

**Comment by lunny** [comment]
@6543 added https://github.com/go-gitea/gitea/issues/7653 on task list

**Comment by 6543** [comment]
> @6543 added #7653 on task list

ok this one liner i could realy add to PR 7604 but i dont get it because it was realy out of topic ...

**Comment by 6543** [comment]
I will be on a trip for a month, so I'm not mad when someone else does tasks :)

**Comment by lunny** [comment]
@6543 Thanks for your work. Have a good time.

**Comment by 6543** [comment]
> @6543 If a repository use pull request, the merged label is unusable. But for others with no pull request, merged label is very usable. I will find time to review your PR.

so if the last commit is includet in default branch and folowing commit on default branch has a message wich "*[Mm]erge*<branch name>*" then it is merged manualy and the merge flag sould also aperar?
is that what you mean?

**Comment by 6543** [comment]
and showing "New Pull Request" Button if there is nothing to merge is noncese (latest commit is included in default branch ...). if you click on it next page tells you: "These branches are equal. There is no need to create a pull request."

**Comment by lunny** [comment]
@6543 good catch

**Comment by 6543** [comment]
https://github.com/go-gitea/gitea/pull/7977 is ready to merge :D
and https://github.com/go-gitea/gitea/issues/7976 is way more complicated ...

**Comment by 6543** [comment]
@lunny have a look at the PR(https://github.com/go-gitea/gitea/pull/7979)?

**Comment by 6543** [comment]
Reverence PR https://github.com/go-gitea/gitea/pull/8449 -> a other todo will be checked soon

**Comment by 6543** [comment]
so it's time I'll close this huge one

lot of things work now ...
Thanks to al who helped me ...
