### ISSUE TITLE
Migration Summary

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8689]
## Supported Migration Routines:
 * [x] Github (wiki,issue,pr,reviews,reactions) (#6290) (#9463) (#9599)
 * [x] GitHub Enterprice ( #11815)
 * [x] Gitlab (#9084, #11147) (self-hosted  #12697)
 * [x] Gitea (#8380, #12657)
 * [x] Codebase (#16768)
 * [ ] [Phabricator](https://github.com/phacility/phabricator) (#20344) 
 * [ ] Gitee (#15945)
 * [ ] [Azure DevOps](https://azure.microsoft.com/en-us/services/devops/)
 * [x] Gogs (#14342)
 * [ ] Bitbucket (#12919)
 * [ ] Trac (#6908) (https://github.com/stevejefferson/trac2gitea)
 * [ ] [Sourcehut](https://man.sr.ht/todo.sr.ht/api.md) [cli tool](https://github.com/xenrox/srhtctl)
 * [ ] Bugzilla (#7802)
 * [ ] RhodeCode
 * [x] OneDev (#16356)
 * [x] GitBucket (#16767)
 * [ ] [Apache Allura](https://forge-allura.apache.org/p/allura/wiki/Home)
 * [ ] [launchpad](https://launchpad.net/) sample go code: [in git-bug](https://github.com/MichaelMure/git-bug/tree/master/bridge/launchpad)

## Features missing on all platform:
* [ ] Projects #12679 #12819
* [ ] Migrate Issues to exist repository #10027
* [x] Migrate and Mirror with LFS #9939 #849
* [ ] Migrate git via SSH #1635
* [ ] Bulk importing of repositories #2569

this will make the whole system more federated again ... sourcecode is - issues not

## Partial Imports ..
* [ ] Import projects/issues from [YouTrack](https://www.jetbrains.com/youtrack)

**Comment by 6543** [comment]
note: https://docs.gitea.io/en-us/migrations-interfaces/

**Comment by lunny** [comment]
And Gitea/Gogs, I have sent a WIP PR to support Gogs.

**Comment by 6543** [comment]
@viceice only a change on the frontend is blocking self-hostet instances -> #9096
If you like to implement migration for bitbucket just have a look at (#9084, #11147) or #11698 or  #7181

**Comment by coldcoff** [comment]
See also https://github.com/go-gitea/gitea/issues/11815

When using repository migrations (mirroring) there is already support for **public** GitHub, that will offer to migrate not only the code, but also Issues, Pull Requests and similar by using the **public** GitHub API to fetch the additional content.

Please make it possible to do the same also when not using the **public** GitHub, i.e. the URL "github.com".

There are **enterprise** GitHub instances out there, typically something like "github.company.com" or so, that will work the same, but they are some "isolated" GitHub.

Currently unfortunately only the code migration is possible from such enterprise GitHub instances.

But as Enterprise GitHub is just "GitHub with different URLs" (and the software version running there is probably a bit older than the public GitHub) the task is hopefully only to make some hardcoded GitHub URLs configurable/extendable.

So it might be a lower hanging fruit. This is not really a new platform / new migration, but an extension to the existing GitHub migration.

**Comment by 6543** [comment]
@coldcoff added to the list

**Comment by lunny** [comment]
@6543 I would like to rename this one as a `migrations` summary issue includes platforms, features, enhancements links and etc.

**Comment by bjornbouetsmith** [comment]
Hi,
Any plans to support migration from on prem Azure DevOps (git) to gitea?

I have tried and it just fails - possibly because authentication in azure devops is not using basic authentication but something else?

It just logs:
~~~
May 19 18:15:27 git gitea[687]: #033[36m2022/05/19 18:15:27 #033[0m#033[32m...ervices/task/task.go:56:#033[32mhandle()#033[0m #033[1;31m[E]#033[0m Run task failed: #033[1mAuthentication failed: Clone: exit status 128 - fatal: Authentication failed for 'http://devops.root.dom/ROOT/common/_git/Helm/'
~~~

I am 100% certain that the username/password combo is correct, since I use it on a daily basis - and also can access the repo from another service - using the exact same combo.

I also have this in my app.ini
~~~
[migrations]
ALLOW_LOCALNETWORKS = true
~~~

My guess is that it is probably because I have a "special" character in my password and when I turn on debug logging I can see the url it tries to clone - and if I copy/paste that URL and do a manual git clone from the prompt - I also get the same:
~~~
fatal: Authentication failed for 'http://devops.root.dom/ROOT/common/_git/Helm/'
~~~

If I do a 
~~~shell
git clone http://root%5Cbbs@devops.root.dom/ROOT/common/_git/Helm
~~~
And manually type in the password - it just works.

I have no idea if its some kind of escaping that happens that messes up the http request inside git - or if its simply wrongly escaped from gitea's side.

Do I just have to accept this?

According to "people" on the internet, then it seems to have been escaped correctly according to https://en.wikipedia.org/wiki/Percent-encoding - but no dice - I have used other systems in the past that did not like my password.

To give a hint about what character that messes it up - its '#' - which I know is bad in a url - but I refuse to change my password just because some systems do not like it.

wget on the other hand just accepts the encoded url - so I am beginning to think its a bug in git.

**Comment by 6543** [comment]
if it's about "raw GIT" migration ... I think it's a bugreport ... nothing we should track here @bjornbouetsmith - could you create a new issue with the info you hosted here :) (github should be able to make your comment a own issue)

**Comment by bjornbouetsmith** [comment]
> if it's about "raw GIT" migration ... I think it's a bugreport ... nothing we should track here @bjornbouetsmith - could you create a new issue with the info you posted here :) (github should be able to make your comment a own issue)

Done - Although I am beginning to think its not a gitea issue - and just a git on linux issue

**Comment by woj-tek** [comment]
Suggestion: Import projects/issues from youtrack
