### ISSUE TITLE
Issues Subscription different Types

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8852]
# Migrate to new Types
current: true (1), false(0)

aim: `IssueWatchModeNone, IssueWatchModeNormal, IssueWatchModeDont, IssueWatchModeAuto`

## ToDo
* [ ] DB migration
* [ ] Update Related code
* [ ] new Function to get Types
* [ ] extend subscription API
      `GET /repos/{owner}/{repo}/issues/{index}/subscriptions/{user}`
* [ ]  ignore issue if unsubscribed but repowatch

## Notes
IssueWatchModeNone = not watching / no DB entry
IssueWatchModeNormal = subscribed to issue (manualy)
IssueWatchModeDont = explisit unsubscribe
IssueWatchModeAuto = subscribed by automation (write a comment at this issue)

RepoWatch should respect IssueWatchModeDont in future ...

**Comment by 6543** [comment]
this should close part of #145 (Automatic subscribe on Open/Comment, etc)

**Comment by 6543** [comment]
WIP PR: #9535
