### ISSUE TITLE
[UI] emoji.js ToDo List

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#8974]
list what come up in #8950,  #8886, ...

## ToDo's
* [ ] Upgrade to latest fork ([hackmdio/emojify.js](https://github.com/hackmdio/emojify.js) since [joypixels/emojify.js](https://github.com/joypixels/emojify.js) is archived)

## Bug's
* [ ]  emoji dont work in markdown list (#8953)

## Enhancements
* [ ] utf8 emoji's (https://github.com/hackmdio/emojify.js/issues/21)
* [ ] optional use of CDN for emoji's
* [ ] custom skin color ? (https://github.com/go-gitea/gitea/pull/8950#issuecomment-553459528)
